---
- name: Instalar Docker
  hosts: vms
  become: yes

  tasks:
    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Instalar pacotes necessários
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      when: ansible_os_family == 'Debian'

    - name: Adicionar chave GPG do Docker
      shell: curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      when: ansible_os_family == 'Debian'

    - name: Adicionar repositório do Docker
      shell: echo "deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      when: ansible_os_family == 'Debian'

    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present
      when: ansible_os_family == 'Debian'
